name: Google sheet

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action

      - name: googlesheet_actions
        uses: rjoydip/googlesheet-actions@0.1.1
        with:
          sheet-id: ${{ secrets.SHEET_ID }}

      - name: echo
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              console.log(${{steps.googlesheet_actions.outputs.result}})

      - name: test
        run: |
          cat $HOME/data.json
