# bare minimal
name: agit webhook bot

on:
  push:
    branches:
      - main

jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
        - name: Webhook
          uses: joelwmale/webhook-action@master
          with:
            url: ${{ secrets.WEBHOOK_URL }}
            headers: '{"repository": "Chedda98/writing-javascript-actions"}'
            body: '{"event": "deployment", "repository": "Chedda98/writing-javascript-actions"}'
