name: JS Actions and googlesheet

on:
    push:
      branches:
        - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}

      - id: googlesheet_actions
        uses: rjoydip/googlesheet-actions@0.1.1
        with:
          sheet-id: ${{ secrets.SHEET_ID }}
      - id: echo
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              console.log(${{steps.googlesheet_actions.outputs.result}})
      - name: test
        run: |
          cat $HOME/data.json
